spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
    ddl-auto: validate
  sql:
    init:
      mode: always
  liquibase:
    change-log: classpath:/db/master.xml
logging:
  level:
    org:
      springframework:
        security: DEBUG



