spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
    ddl-auto: validate
  sql:
    init:
      mode: always
  liquibase:
    change-log: classpath:/db/master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: testowehubert@gmail.com
    password: dkblnzjipjodhkdt
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocole: smtp
logging:
  level:
    org:
      springframework:
        security: DEBUG



